version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: miko-nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: miko-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  mongodb:
    image: mongo:7
    container_name: miko-mongodb
    restart: unless-stopped
    # Comment lệnh ports để ẩn MongoDB ra internet - chỉ truy cập internally
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Matkhau2025
      MONGO_INITDB_DATABASE: miko-n8n
    volumes:
      - mongodb_data:/data/db
    networks:
      - miko-network
    env_file:
      - .env.production

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miko-nextjs-app
    restart: unless-stopped
    # Comment port 8888 để chỉ truy cập qua nginx
    # ports:
    #   - "8888:8888"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - REFRESH_TOKEN_EXPIRES=${REFRESH_TOKEN_EXPIRES:-30d}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
    depends_on:
      - mongodb
    networks:
      - miko-network
    # Để sử dụng file .env.production, thêm dòng sau:
    env_file:
      - .env.production

volumes:
  mongodb_data:
    driver: local

networks:
  miko-network:
    driver: bridge
